### ISSUE TITLE
部署网站

### ISSUE THREAD

**Issue by CyrusYip** [hhx546642451/tiangou#3]
可以用 Netlify 或 Vercel 部署网站，这样就可以在线看了。

**Comment by huhexian** [comment]
🤣我不太会用这两个，索性在自己服务器上搭建了一个：http://t.huhexian.cn/

**Comment by CyrusYip** [comment]
在那两个网站用 GitHub 帐户登陆，然后导入这个仓库就行了，它弄好之后就会给你分配个网站，你也可以自己设置。不过你用自己的服务器弄也行。
